#!/bin/bash
curl -s https://git.parabola.nu/blacklist.git/plain/blacklist.txt | grep "nonfree" > ~/.cache/blacklis
pacman -Qq | while read line ; do
   grep -w  "^$line:" ~/.cache/blacklist | cut -d: -f1,5,6
done
